import matplotlib.pyplot as plt
import numpy as a
f=input("enter the frequency")
fs=input("enter the sampling frequency")
x=a.arange(0,50,0.5)
y=a.sin(2*a.pi*f*x/fs)
plt.subplot(3,1,1)
plt.plot(x,y)
plt.title('sinwave')
plt.xlabel('time')
plt.ylabel('amplitude')
b=a.cos(2*a.pi*f*x/fs)
plt.subplot(3,1,2)
plt.plot(x,b)
plt.title('coswave')
plt.xlabel('time')
plt.ylabel('amplitude')
c=y+b
plt.subplot(3,1,3)
plt.plot(x,c)
plt.title('addition of cos and sin wave')
plt.xlabel('time')
plt.ylabel('amplitude')
plt.show()